--  TPC-H — PostgreSQL
--  Execute este arquivo no pgAdmin 4 (Query Tool) após criar
--  o banco de dados 'tpch'.
--
--  Antes de executar:
--  Substitua todos os trechos que contêm:
--      C:\caminho\para\dbgen.data\
--  pelo caminho real da pasta dbgen.data no seu computador.
--  Exemplo:
--      D:\Faculdade\2026.1\BD2\Benchmark TPC-H\dbgen.data\

-- 1. Criar o schema
CREATE SCHEMA "tpc-h";
SET search_path TO "tpc-h";

-- 2. Criar as tabelas
CREATE TABLE PART (
    P_PARTKEY     INTEGER       NOT NULL,
    P_NAME        VARCHAR(55),
    P_MFGR        CHAR(25),
    P_BRAND       CHAR(10),
    P_TYPE        VARCHAR(25),
    P_SIZE        INTEGER,
    P_CONTAINER   CHAR(10),
    P_RETAILPRICE DECIMAL(12,2),
    P_COMMENT     VARCHAR(23),
    CONSTRAINT PART_PK PRIMARY KEY (P_PARTKEY)
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY   INTEGER      NOT NULL,
    S_NAME      CHAR(25),
    S_ADDRESS   VARCHAR(40),
    S_NATIONKEY INTEGER,
    S_PHONE     CHAR(15),
    S_ACCTBAL   DECIMAL(12,2),
    S_COMMENT   VARCHAR(101),
    CONSTRAINT SUPPLIER_PK PRIMARY KEY (S_SUPPKEY)
);

CREATE TABLE PARTSUPP (
    PS_PARTKEY   INTEGER       NOT NULL,
    PS_SUPPKEY   INTEGER       NOT NULL,
    PS_AVAILQTY  INTEGER,
    PS_SUPPLYCOST DECIMAL(12,2),
    PS_COMMENT   VARCHAR(199),
    CONSTRAINT PARTSUPP_PK PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE CUSTOMER (
    C_CUSTKEY    INTEGER      NOT NULL,
    C_NAME       CHAR(25),
    C_ADDRESS    VARCHAR(40),
    C_NATIONKEY  INTEGER,
    C_PHONE      CHAR(15),
    C_ACCTBAL    DECIMAL(12,2),
    C_MKTSEGMENT VARCHAR(10),
    C_COMMENT    TEXT,
    CONSTRAINT CUSTUMER_PK PRIMARY KEY (C_CUSTKEY)
);

CREATE TABLE ORDERS (
    O_ORDERKEY      INTEGER       NOT NULL,
    O_CUSTKEY       INTEGER,
    O_ORDERSTATUS   CHAR(1),
    O_TOTALPRICE    DECIMAL(12,2),
    O_ORDERDATE     TIMESTAMP,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK         CHAR(15),
    O_SHIPPRIORITY  INTEGER,
    O_COMMENT       TEXT,
    CONSTRAINT ORDERS_PK PRIMARY KEY (O_ORDERKEY)
);

CREATE TABLE LINEITEM (
    L_ORDERKEY      INTEGER       NOT NULL,
    L_PARTKEY       INTEGER,
    L_SUPPKEY       INTEGER,
    L_LINENUMBER    INTEGER       NOT NULL,
    L_QUANTITY      DECIMAL(12,2),
    L_EXTENDEDPRICE DECIMAL(12,2),
    L_DISCOUNT      DECIMAL(12,2),
    L_TAX           DECIMAL(12,2),
    L_RETURNFLAG    CHAR(1),
    L_LINESTATUS    CHAR(1),
    L_SHIPDATE      TIMESTAMP,
    L_COMMITDATE    TIMESTAMP,
    L_RECEIPTDATE   TIMESTAMP,
    L_SHIPINSTRUCT  CHAR(25),
    L_SHIPMODE      CHAR(10),
    L_COMMENT       TEXT,
    CONSTRAINT LINEITEM_PK PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

CREATE TABLE NATION (
    N_NATIONKEY INTEGER      NOT NULL,
    N_NAME      CHAR(25),
    N_REGIONKEY INTEGER,
    N_COMMENT   VARCHAR(152),
    CONSTRAINT NATION_PK PRIMARY KEY (N_NATIONKEY)
);

CREATE TABLE REGION (
    R_REGIONKEY INTEGER      NOT NULL,
    R_NAME      CHAR(25),
    R_COMMENT   VARCHAR(152),
    CONSTRAINT REGION_PK PRIMARY KEY (R_REGIONKEY)
);

-- 3. Importar os dados
-- Substitua C:\caminho\para\dbgen.data\ pelo caminho real no seu computador

ALTER TABLE nation ADD COLUMN stub CHAR(1);
COPY nation(N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\nation.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE nation DROP COLUMN stub;

ALTER TABLE region ADD COLUMN stub CHAR(1);
COPY region(R_REGIONKEY, R_NAME, R_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\region.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE region DROP COLUMN stub;

ALTER TABLE supplier ADD COLUMN stub CHAR(1);
COPY supplier(S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\supplier.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE supplier DROP COLUMN stub;

ALTER TABLE part ADD COLUMN stub CHAR(1);
COPY part(P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\part.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE part DROP COLUMN stub;

ALTER TABLE partsupp ADD COLUMN stub CHAR(1);
COPY partsupp(PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST, PS_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\partsupp.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE partsupp DROP COLUMN stub;

ALTER TABLE customer ADD COLUMN stub CHAR(1);
COPY customer(C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\customer.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE customer DROP COLUMN stub;

ALTER TABLE orders ADD COLUMN stub CHAR(1);
COPY orders(O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY, O_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\orders.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE orders DROP COLUMN stub;

ALTER TABLE lineitem ADD COLUMN stub CHAR(1);
COPY lineitem(L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT, stub)
FROM 'C:\caminho\para\dbgen.data\lineitem.tbl'
WITH (FORMAT csv, DELIMITER '|', QUOTE E'\x01');
ALTER TABLE lineitem DROP COLUMN stub;

-- 4. Adicionar as chaves estrangeiras
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK  FOREIGN KEY (S_NATIONKEY)          REFERENCES NATION   (N_NATIONKEY);
ALTER TABLE PARTSUPP ADD CONSTRAINT PARTSUPP_FK1 FOREIGN KEY (PS_PARTKEY)           REFERENCES PART     (P_PARTKEY);
ALTER TABLE PARTSUPP ADD CONSTRAINT PARTSUPP_FK2 FOREIGN KEY (PS_SUPPKEY)           REFERENCES SUPPLIER (S_SUPPKEY);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTUMER_FK  FOREIGN KEY (C_NATIONKEY)          REFERENCES NATION   (N_NATIONKEY);
ALTER TABLE ORDERS   ADD CONSTRAINT ORDERS_FK    FOREIGN KEY (O_CUSTKEY)            REFERENCES CUSTOMER (C_CUSTKEY);
ALTER TABLE LINEITEM ADD CONSTRAINT LINEITEM_FK1 FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP (PS_PARTKEY, PS_SUPPKEY);
ALTER TABLE LINEITEM ADD CONSTRAINT LINEITEM_FK2 FOREIGN KEY (L_ORDERKEY)           REFERENCES ORDERS   (O_ORDERKEY);
ALTER TABLE LINEITEM ADD CONSTRAINT LINEITEM_FK3 FOREIGN KEY (L_PARTKEY)            REFERENCES PART     (P_PARTKEY);
ALTER TABLE LINEITEM ADD CONSTRAINT LINEITEM_FK4 FOREIGN KEY (L_SUPPKEY)            REFERENCES SUPPLIER (S_SUPPKEY);
ALTER TABLE NATION   ADD CONSTRAINT NATION_FK    FOREIGN KEY (N_REGIONKEY)          REFERENCES REGION   (R_REGIONKEY);
